# Generated by Django 4.2 on 2023-05-02 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('duration_in_weeks', models.IntegerField()),
                ('goals', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('healthy_lifestyle', 'Healthy Lifestyle')], max_length=50)),
                ('allowed_foods', models.TextField()),
                ('restricted_foods', models.TextField()),
                ('meal_plan', models.CharField(choices=[('vegan', 'Vegan'), ('keto', 'Keto'), ('mediterranean', 'Mediterranean')], max_length=50)),
                ('nutritional_info', models.CharField(choices=[('low_calorie', 'Low Calorie'), ('high_protein', 'High Protein'), ('low_fat', 'Low Fat')], max_length=50)),
                ('cost_in_usd', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000.0)])),
            ],
        ),
    ]
