# Generated by Django 4.2 on 2023-05-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='text',
            new_name='diet_plan',
        ),
    ]
